apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp
  namespace: lae-production
  labels:
    app: warp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: warp
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: warp
    spec:
      serviceAccountName: azure-workload-identity-service-account
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      containers:
      - name: warp
        image: businessschool.azurecr.io/education/warp:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "200m"
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
          - name: secrets-store-inline               # mount the keyvault secret as volume inside the container
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
        - name: WARP_DATABASE
          valueFrom:
            secretKeyRef:
              name: warp-secret
              key: WARP-DATABASE

      imagePullSecrets:
        - name: businessschool-azurecr-io-regsecret
      volumes:
        - name: secrets-store-inline               # keyvault csi secret volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-warp-lae # metadata.name in secret-provider-class.yaml
