apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-warp-lae
  namespace: lae-production
spec:
  secretObjects:
    - data:
        - key: WARP-DATABASE
          objectName: WARP-DATABASE
      secretName: warp-secret
      type: Opaque
  provider: azure
  parameters:
    keyvaultName:  k8s-lae-production
    objects:  |
      array:
        - |
          objectName: WARP-DATABASE
          objectType: secret
          objectVersion: ""
    tenantId: "01467f4f-db36-41a3-a52d-f91dad816bab"
    clientID: "44a007e4-5299-4ca2-84d5-1d31a055dea2"
