apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-warp-lae
  namespace: lae-development
spec:
  secretObjects:
    - data:
        - key: WARP-DATABASE
          objectName: WARP-DATABASE
      secretName: warp-secret
      type: Opaque
  provider: azure
  parameters:
    keyvaultName:  k8s-lae-development
    objects:  |
      array:
        - |
          objectName: WARP-DATABASE
          objectType: secret
          objectVersion: ""
    tenantId: "01467f4f-db36-41a3-a52d-f91dad816bab"
    clientID: "745e437d-a575-4a8e-a04b-42ff33ad4133"
